const state = { user: null, dashboard: null, notifications: [], source: null, currentView: "overview" };
const $ = (selector) => document.querySelector(selector);
const loginView = $("#login-view");
const adminView = $("#admin-view");
const content = $("#workspace-content");
const message = $("#site-message");

function escapeHtml(value) { return String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[char])); }
function arabicNumber(value) { return new Intl.NumberFormat("ar-SY").format(Number(value || 0)); }
function money(value) { return `${arabicNumber(value)} ل.س`; }
function dateLabel(value) { return value ? new Intl.DateTimeFormat("ar-SY", { dateStyle:"medium", timeStyle:"short" }).format(new Date(value)) : "—"; }
function statusTone(status) { return ["requested", "pending", "pending_admin", "code_sent", "locked"].includes(status) ? "warning" : ["delivered", "approved", "ready", "download_confirmed", "verified"].includes(status) ? "success" : ""; }
function statusLabel(status) { const map = { requested:"بانتظار سائق", accepted:"تم القبول", arriving:"في الطريق", awaiting_otp:"بانتظار الرمز", delivered:"مكتمل", cancelled:"ملغى", pending:"معلّق", pending_admin:"بانتظار مراجعة المدير", code_sent:"أُرسل الرمز", locked:"محاولات كثيرة", verified:"متحقق", expired:"منتهي", rejected:"مرفوض", approved:"موافق", ready:"جاهز", download_confirmed:"تم التنزيل", generating:"قيد الإنشاء", purged:"مؤرشف" }; return map[status] || status; }
function notify(text, isError = false) { message.textContent = text; message.className = `site-message${isError ? " error" : ""}`; message.hidden = false; window.setTimeout(() => { message.hidden = true; }, 6000); }
async function api(url, options = {}) { const response = await fetch(url, { credentials:"same-origin", headers:{ "Content-Type":"application/json", ...(options.headers || {}) }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(data.error || "REQUEST_FAILED"); error.status = response.status; throw error; } return data; }
function showLoading() { content.innerHTML = $("#loading-template").innerHTML; }
function activateView(view) { state.currentView = view; document.querySelectorAll(".nav-link").forEach((item) => item.classList.toggle("active", item.dataset.view === view)); $("#page-title").textContent = view === "overview" ? "نظرة عامة" : view === "operations" ? "الطلبات والسفراء" : view === "verifications" ? "طلبات التحقق" : "التقارير المالية"; if (view === "overview") renderOverview(); if (view === "operations") renderOperations(); if (view === "verifications") renderVerifications(); if (view === "reports") renderReports(); }

function renderOverview() { const data = state.dashboard; if (!data) return showLoading(); const metrics = data.metrics; const orders = data.orders || []; const drivers = data.drivers || []; content.innerHTML = `
  <section class="hero"><div><p class="eyebrow">تشغيل اليوم</p><h2>صباح الخير، ${escapeHtml(state.user.name)}</h2><p>نظرة مستقلة على عمليات التوصيل؛ لا تتطلب فتح تطبيق الهاتف.</p></div><div class="date-stamp">${new Intl.DateTimeFormat("ar-SY", { weekday:"long", day:"numeric", month:"long", year:"numeric" }).format(new Date())}</div></section>
  <section class="metric-grid"><article class="metric-card"><span class="label">طلبات اليوم</span><strong>${arabicNumber(metrics.todayOrders)}</strong><small>حركة اليوم الحالية</small></article><article class="metric-card green"><span class="label">سائقون نشطون</span><strong>${arabicNumber(metrics.activeDrivers)}</strong><small>ضمن الحسابات المفعلة</small></article><article class="metric-card amber"><span class="label">طلبات التفعيل</span><strong>${arabicNumber(metrics.pendingDrivers)}</strong><small>تحتاج قرار الإدارة</small></article><article class="metric-card blue"><span class="label">إيراد اليوم</span><strong>${money(metrics.revenue)}</strong><small>من الطلبات المكتملة</small></article><article class="metric-card"><span class="label">ورديات مفتوحة</span><strong>${arabicNumber(metrics.openShifts)}</strong><small>تحتاج تسوية لاحقاً</small></article></section>
  <section class="dashboard-grid"><article class="card"><div class="card-head"><div><h3>توزع الأسطول</h3><p>آخر مواقع السائقين المفعّلين</p></div><span class="badge success">${arabicNumber(drivers.length)} متصلون</span></div><div class="map-panel"><b class="map-label">حماة</b><i class="map-pin one">س</i><i class="map-pin two active">ف</i><i class="map-pin three">م</i><span class="map-legend">تحديث موقع السائقين نشط</span></div></article><article class="card"><div class="card-head"><div><h3>تنبيهات تحتاج متابعة</h3><p>آخر الطلبات وتغيّرات السائقين</p></div><button class="text-button" data-action="open-notices">عرض الكل</button></div><div class="action-list">${state.notifications.slice(0,3).map((item) => `<div class="action-item"><i class="round-icon ${item.level === "warning" ? "amber" : item.level === "success" ? "green" : ""}">${item.kind === "order" ? "#" : "س"}</i><div><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.detail)}</span></div><span class="badge ${item.level === "warning" ? "warning" : item.level === "success" ? "success" : ""}">${dateLabel(item.createdAt)}</span></div>`).join("") || `<p class="empty">لا توجد تنبيهات حالياً.</p>`}</div></article></section>
  <section class="card" style="margin-top:16px"><div class="card-head"><div><h3>آخر الطلبات</h3><p>آخر تحديثات حالة التوصيل</p></div><button class="text-button" data-view-link="operations">إدارة العمليات</button></div><table class="data-table"><thead><tr><th>الطلب والمسار</th><th>الحالة</th><th>السائق</th><th>آخر تحديث</th></tr></thead><tbody>${orders.map((order) => `<tr><td><strong>#${escapeHtml(order.id.slice(0,8))}</strong><small>${escapeHtml(order.source_address)} ← ${escapeHtml(order.destination_address)}</small></td><td><span class="badge ${statusTone(order.status)}">${statusLabel(order.status)}</span></td><td>${order.driver_id ? "مُعيّن" : "—"}</td><td>${dateLabel(order.updated_at)}</td></tr>`).join("") || `<tr><td colspan="4" class="empty">لا توجد طلبات مسجلة.</td></tr>`}</tbody></table></section><p class="data-note">تعرض البوابة بيانات محفوظة على الخادم وتتحقق من صلاحية المدير لكل طلب.</p>`;
  bindContentActions(); }
function renderOperations() { const data = state.dashboard; const pending = state.notifications.filter((n) => n.kind === "driver"); content.innerHTML = `<section class="hero"><div><p class="eyebrow">إدارة مباشرة</p><h2>الطلبات والسائقون</h2><p>راجع الطلبات الجديدة وحالات التفعيل من موقع الإدارة المستقل.</p></div></section><section class="operations-layout"><article class="card"><div class="card-head"><div><h3>سجل الطلبات</h3><p>أحدث ما وصل إلى منصة التوصيل</p></div><span class="badge warning">${arabicNumber((data.orders || []).filter((o) => o.status === "requested").length)} بانتظار تعيين</span></div><table class="data-table"><thead><tr><th>المعرف</th><th>المسار</th><th>الدفع</th><th>الحالة</th></tr></thead><tbody>${(data.orders || []).map((order) => `<tr><td><strong>#${escapeHtml(order.id.slice(0,8))}</strong><small>${money(order.final_price || order.estimated_price)}</small></td><td>${escapeHtml(order.source_address)}<small>${escapeHtml(order.destination_address)}</small></td><td>${money(order.estimated_price)}</td><td><span class="badge ${statusTone(order.status)}">${statusLabel(order.status)}</span></td></tr>`).join("") || `<tr><td colspan="4" class="empty">لا توجد طلبات بعد.</td></tr>`}</tbody></table></article><section class="split-card"><article class="card"><div class="card-head"><div><h3>سائقون مفعّلون</h3><p>الحسابات النشطة</p></div><span class="badge success">${arabicNumber((data.drivers || []).length)} نشطون</span></div><div class="action-list">${(data.drivers || []).map((driver) => `<div class="action-item"><i class="round-icon green">${escapeHtml((driver.name || "س").slice(0,1))}</i><div><strong>${escapeHtml(driver.name || "سائق جربوع")}</strong><span>${driver.last_location_at ? `آخر موقع: ${dateLabel(driver.last_location_at)}` : "لم يرسل الموقع بعد"}</span></div><span class="badge success">مفعّل</span></div>`).join("") || `<p class="empty">لا يوجد سائقون نشطون.</p>`}</div></article><article class="card"><div class="card-head"><div><h3>ملفات التحقق</h3><p>آخر تغيرات ملفات السائقين</p></div></div><div class="action-list">${pending.map((item) => `<div class="action-item"><i class="round-icon amber">س</i><div><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.detail)}</span></div><span class="badge warning">معلّق</span></div>`).join("") || `<p class="empty">لا توجد ملفات معلقة.</p>`}</div></article></section></section>`; }
async function renderVerifications() { showLoading(); try { const result = await api("/admin/api/verifications"); const requests = result.requests || []; content.innerHTML = `<section class="hero"><div><p class="eyebrow">دخول برمز تحقق</p><h2>طلبات العميل والسفير</h2><p>أنشئ الرمز هنا ثم افتح WhatsApp لإرساله يدوياً إلى الرقم المسجل. لا يُحفظ الرمز كنص صريح في النظام.</p></div></section><section class="card"><div class="card-head"><div><h3>طلبات بانتظار المراجعة</h3><p>الرمز صالح عشر دقائق فقط وتظهر بيانات كل متقدم للمديرين المصرح لهم.</p></div><span class="badge warning">${arabicNumber(requests.length)} طلبات</span></div><div class="action-list">${requests.map((request) => `<div class="action-item"><i class="round-icon ${request.requested_role === "driver" ? "amber" : "green"}">${request.requested_role === "driver" ? "س" : "ع"}</i><div><strong>${escapeHtml(request.full_name)} · ${request.requested_role === "driver" ? "سفير" : "عميل"}</strong><span>${escapeHtml(request.phone)}${request.vehicle_type ? ` · ${escapeHtml(request.vehicle_type)}` : ""} · ${statusLabel(request.status)}</span></div><button class="small-action" data-verification-id="${escapeHtml(request.id)}">${request.status === "code_sent" ? "إعادة إرسال الرمز" : "إرسال الرمز عبر WhatsApp"}</button></div>`).join("") || `<p class="empty">لا توجد طلبات تحقق معلقة.</p>`}</div></section>`; bindContentActions(); } catch (error) { handleApiError(error); } }
async function renderReports() { showLoading(); try { const result = await api("/admin/api/reports"); const reports = result.reports || []; content.innerHTML = `<section class="hero"><div><p class="eyebrow">تقارير وأرشفة</p><h2>التقارير المالية والتشغيلية</h2><p>أنشئ ملف PDF شهرياً ثم نزّله مباشرة من البوابة مع تسجيل تأكيد التنزيل.</p></div></section><section class="reports-layout"><article class="card"><div class="card-head"><div><h3>إنشاء تقرير شهري</h3><p>تجميع الطلبات والورديات في ملف PDF قابل للتحميل.</p></div><span class="badge">PDF</span></div><div class="report-controls"><label>الشهر<div><input id="report-month" type="month" value="${new Date(new Date().setMonth(new Date().getMonth()-1)).toISOString().slice(0,7)}" /></div></label><button id="generate-report" class="primary-button" type="button">إنشاء أو تحديث التقرير</button></div><p class="security-note">يمكن للمدير المصرح فقط إنشاء التقرير أو تنزيله، وتسجل المنصة تأكيد التنزيل قبل أي أرشفة لاحقة.</p></article><article class="card"><div class="card-head"><div><h3>ملفات PDF المتاحة</h3><p>تنزيل مباشر بصلاحية مؤقتة وآمنة.</p></div><span class="badge success">${arabicNumber(reports.length)} تقارير</span></div><div>${reports.map((report) => `<div class="report-row"><div><strong>${escapeHtml(String(report.report_month).slice(0,7))}</strong><span>${report.generated_at ? `أُنشئ: ${dateLabel(report.generated_at)}` : "بانتظار الإنشاء"}</span></div><span class="badge ${statusTone(report.status)}">${statusLabel(report.status)}</span><button class="download-link" data-report-id="${escapeHtml(report.id)}" ${["ready","download_confirmed"].includes(report.status) ? "" : "disabled"}>تنزيل PDF</button></div>`).join("") || `<p class="empty">لا توجد تقارير جاهزة بعد. اختر شهراً لإنشاء التقرير.</p>`}</div></article></section>`; bindContentActions(); } catch (error) { handleApiError(error); } }
function renderNotifications() { const list = $("#notification-list"); list.innerHTML = state.notifications.map((item) => `<div class="notification-entry"><i class="notice-dot ${item.level}"></i><div class="notice-copy"><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.detail)} · ${dateLabel(item.createdAt)}</span></div></div>`).join("") || `<p class="empty">لا توجد تنبيهات جديدة.</p>`; const count = $("#notification-count"); count.textContent = String(state.notifications.length); count.classList.toggle("visible", state.notifications.length > 0); }
function bindContentActions() { document.querySelectorAll("[data-view-link]").forEach((button) => button.addEventListener("click", () => activateView(button.dataset.viewLink))); document.querySelectorAll("[data-action='open-notices']").forEach((button) => button.addEventListener("click", openNotifications)); const generator = $("#generate-report"); if (generator) generator.addEventListener("click", generateReport); document.querySelectorAll("[data-report-id]").forEach((button) => button.addEventListener("click", () => downloadReport(button.dataset.reportId, button))); document.querySelectorAll("[data-verification-id]").forEach((button) => button.addEventListener("click", () => sendVerificationCode(button.dataset.verificationId, button))); }
async function sendVerificationCode(requestId, button) { button.disabled = true; button.textContent = "جارٍ تجهيز الرابط…"; try { const result = await api(`/admin/api/verifications/${encodeURIComponent(requestId)}/send-code`, { method:"POST", body:"{}" }); window.open(result.whatsappUrl, "_blank", "noopener,noreferrer"); notify("فُتح WhatsApp بالرسالة الجاهزة. أرسل الرمز إلى الرقم ثم انتظر إدخاله في التطبيق."); await renderVerifications(); } catch (error) { handleApiError(error); button.disabled = false; button.textContent = "إرسال الرمز عبر WhatsApp"; } }
async function generateReport() { const input = $("#report-month"); const button = $("#generate-report"); const value = input.value ? `${input.value}-01` : ""; button.disabled = true; button.textContent = "جارٍ الإنشاء…"; try { const response = await api("/admin/api/reports/generate", { method:"POST", body:JSON.stringify({ reportMonth:value }) }); notify(response.result?.generated ? "تم إنشاء التقرير، وهو الآن جاهز للتحميل." : "تمت مراجعة حالة التقرير. قد يكون موجوداً بالفعل."); await renderReports(); } catch (error) { handleApiError(error); button.disabled = false; button.textContent = "إنشاء أو تحديث التقرير"; } }
async function downloadReport(reportId, button) { button.disabled = true; button.textContent = "جارٍ التحضير…"; try { const response = await api(`/admin/api/reports/${encodeURIComponent(reportId)}/download`, { method:"POST", body:"{}" }); const anchor = document.createElement("a"); anchor.href = response.url; anchor.download = ""; anchor.rel = "noopener"; document.body.appendChild(anchor); anchor.click(); anchor.remove(); notify("بدأ تنزيل ملف PDF. تم تسجيل تأكيد التنزيل في سجل التقرير."); button.textContent = "تم التحميل"; } catch (error) { handleApiError(error); button.disabled = false; button.textContent = "تنزيل PDF"; } }
async function refreshDashboard() { try { state.dashboard = await api("/admin/api/dashboard"); state.notifications = state.dashboard.notifications || []; renderNotifications(); if (state.currentView === "overview") renderOverview(); if (state.currentView === "operations") renderOperations(); } catch (error) { handleApiError(error); } }
function openNotifications() { $("#notification-drawer").hidden = false; renderNotifications(); }
function subscribeNotifications() { if (state.source) state.source.close(); state.source = new EventSource("/admin/api/notifications/stream"); state.source.addEventListener("notifications", (event) => { state.notifications = JSON.parse(event.data); renderNotifications(); if (state.currentView === "overview") renderOverview(); }); state.source.addEventListener("error", () => { window.setTimeout(refreshDashboard, 1200); }); }
async function login(event) { event.preventDefault(); const button = $("#login-button"); const errorBox = $("#login-error"); const body = { phone: $("#phone").value.trim(), password: $("#password").value }; button.disabled = true; button.textContent = "جارٍ التحقق…"; errorBox.hidden = true; try { const result = await api("/admin/api/login", { method:"POST", body:JSON.stringify(body) }); state.user = result.user; await openAdmin(); } catch (error) { errorBox.textContent = error.status === 403 ? "هذا الحساب لا يملك صلاحية مدير نشطة." : error.status === 429 ? "تم إيقاف المحاولة مؤقتاً للحماية. حاول لاحقاً." : "تعذر تسجيل الدخول. تحقق من البيانات ثم أعد المحاولة."; errorBox.hidden = false; } finally { button.disabled = false; button.textContent = "دخول آمن إلى البوابة"; } }
async function openAdmin() { loginView.hidden = true; adminView.hidden = false; $("#manager-name").textContent = state.user.name || "مدير جربوع"; $("#manager-initial").textContent = (state.user.name || "م").slice(0,1); await refreshDashboard(); subscribeNotifications(); }
async function logout() { try { await api("/admin/api/logout", { method:"POST", body:"{}" }); } finally { if (state.source) state.source.close(); state.source = null; adminView.hidden = true; loginView.hidden = false; $("#password").value = ""; notify("تم تسجيل الخروج بأمان."); } }
function handleApiError(error) { if (error.status === 401 || error.status === 403) { logout(); return; } notify("تعذر تنفيذ الطلب الآن. تحقق من الاتصال أو من حالة الخدمة.", true); }
$("#login-form").addEventListener("submit", login); $("#logout-button").addEventListener("click", logout); $("#notification-button").addEventListener("click", openNotifications); $("#close-notifications").addEventListener("click", () => { $("#notification-drawer").hidden = true; }); $("#sidebar-nav").addEventListener("click", (event) => { const button = event.target.closest("[data-view]"); if (button) activateView(button.dataset.view); });
(async () => { try { const result = await api("/admin/api/session"); state.user = result.user; await openAdmin(); } catch { loginView.hidden = false; } })();
