import * as Haptics from "expo-haptics";
import * as ImagePicker from "expo-image-picker";
import { Image } from "expo-image";
import { useMemo, useState } from "react";
import { Alert, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { VALID_HAMA_STOPS, formatSyp } from "@/shared/jarbou3";
import { HamaMap } from "@/components/hama-map";

type Role = "customer" | "driver" | "admin";
type CustomerPage = "home" | "order" | "track" | "otp";
type DriverPage = "home" | "verify" | "drive" | "deliver";

const dark = "#1E1E1E";
const gray = "#4A4A4A";

function haptic() {
  if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
}

function Action({ title, onPress, kind = "solid" }: { title: string; onPress: () => void; kind?: "solid" | "outline" | "dark" }) {
  return (
    <Pressable onPress={() => { haptic(); onPress(); }} style={({ pressed }) => [styles.action, kind === "outline" && styles.actionOutline, kind === "dark" && styles.actionDark, pressed && styles.pressed]}>
      <Text style={[styles.actionText, kind === "outline" && styles.actionOutlineText]}>{title}</Text>
    </Pressable>
  );
}

function Tag({ children, status = false }: { children: string; status?: boolean }) {
  return <View style={[styles.tag, status && styles.tagStatus]}><Text style={[styles.tagText, status && styles.tagStatusText]}>{children}</Text></View>;
}

function Mark({ small = false }: { small?: boolean }) {
  return <View style={[styles.mark, small && styles.markSmall]}><Image source={require("@/assets/images/icon.png")} style={styles.markImage} contentFit="cover" /></View>;
}

function Heading({ eyebrow, title, aside }: { eyebrow?: string; title: string; aside?: string }) {
  return (
    <View style={styles.headingRow}>
      <View>{eyebrow ? <Text style={styles.eyebrow}>{eyebrow}</Text> : null}<Text style={styles.heading}>{title}</Text></View>
      {aside ? <Text style={styles.aside}>{aside}</Text> : null}
    </View>
  );
}

function RoleSwitch({ role, onSelect }: { role: Role; onSelect: (role: Role) => void }) {
  return <View style={styles.roleSwitch}>{(["customer", "driver", "admin"] as Role[]).map((option) => <Pressable key={option} onPress={() => onSelect(option)} style={[styles.role, role === option && styles.roleSelected]}><Text style={[styles.roleText, role === option && styles.roleTextSelected]}>{option === "customer" ? "عميل" : option === "driver" ? "سائق" : "إدارة"}</Text></Pressable>)}</View>;
}

function Customer() {
  const [page, setPage] = useState<CustomerPage>("home");
  const [source, setSource] = useState<string>(VALID_HAMA_STOPS[0]);
  const [destination, setDestination] = useState<string>(VALID_HAMA_STOPS[3]);
  const [payment, setPayment] = useState<"نقدي" | "شام كاش">("نقدي");
  const [otp, setOtp] = useState("");
  const price = useMemo(() => source === destination ? 6000 : 12000, [source, destination]);

  if (page === "order") return <ScrollView contentContainerStyle={styles.scroll}><Top title="طلب توصيل" back={() => setPage("home")} /><HamaMap compact /><View style={styles.card}><Heading eyebrow="داخل نطاق الخدمة" title="اختر العناوين" /><Text style={styles.label}>المصدر</Text><StopButtons current={source} setCurrent={setSource} choices={VALID_HAMA_STOPS.slice(0, 4)} /><Text style={styles.label}>الوجهة</Text><StopButtons current={destination} setCurrent={setDestination} choices={VALID_HAMA_STOPS.slice(3)} /><View style={styles.quote}><View><Text style={styles.quoteLabel}>السعر التقديري</Text><Text style={styles.quoteValue}>{formatSyp(price)}</Text></View><View style={styles.quoteLine} /><View><Text style={styles.quoteLabel}>المسافة والوقت</Text><Text style={styles.quoteValueSmall}>٤٫٢ كم · ١٤ دقيقة</Text></View></View><Text style={styles.label}>طريقة الدفع</Text><View style={styles.paymentRow}>{(["نقدي", "شام كاش"] as const).map((method) => <Pressable key={method} onPress={() => setPayment(method)} style={[styles.payment, payment === method && styles.paymentSelected]}><Text style={styles.paymentText}>{method}</Text></Pressable>)}</View><Action title={`تأكيد الطلب · ${formatSyp(price)}`} onPress={() => source === destination ? Alert.alert("تحقق من العناوين", "اختر مصدرًا ووجهة مختلفين داخل حماة.") : setPage("track")} /></View></ScrollView>;

  if (page === "track") return <View style={styles.fill}><HamaMap driver /><View style={styles.trackSheet}><View style={styles.handle} /><View style={styles.split}><Tag status>السائق في الطريق</Tag><Text style={styles.muted}>طلب #J-2048</Text></View><Text style={styles.trackTitle}>سليم متجه إلى المصدر</Text><Text style={styles.copy}>دراجة كهربائية رمادية · تبقى نحو ٧ دقائق</Text><View style={styles.driverBox}><View style={styles.avatar}><Text style={styles.avatarText}>س</Text></View><View style={styles.flex}><Text style={styles.driverName}>سليم ع.</Text><Text style={styles.mutedRight}>سائق جربوع موثّق · ٤٫٩</Text></View><Pressable onPress={() => Alert.alert("اتصال", "سيُفتح الاتصال المباشر بالسائق عند تشغيل أرقام الخدمة.")} style={styles.minor}><Text style={styles.minorText}>اتصال</Text></Pressable></View><View style={styles.timeline}><Text style={styles.done}>● تم قبول طلبك</Text><Text style={styles.live}>● السائق متجه إلى المصدر</Text><Text style={styles.future}>○ استلام رمز التسليم</Text></View><Action title="لدي رمز الاستلام" onPress={() => setPage("otp")} /><Action title="العودة للرئيسية" kind="outline" onPress={() => setPage("home")} /></View></View>;

  if (page === "otp") return <View style={styles.fill}><Top title="تأكيد الاستلام" back={() => setPage("track")} /><View style={styles.centered}><View style={styles.otpBadge}><Text style={styles.otpBadgeText}>OTP</Text></View><Text style={styles.centerTitle}>أدخل رمز الاستلام</Text><Text style={styles.centerCopy}>يشاركك السائق الرمز عند وصول الطلب. لا تؤكده قبل الاستلام.</Text><TextInput style={styles.otp} value={otp} onChangeText={setOtp} keyboardType="number-pad" maxLength={4} placeholder="••••" placeholderTextColor="#AAA" textAlign="center" /><Action title="تأكيد الرمز" onPress={() => otp.length === 4 ? Alert.alert("تم التأكيد", "سيطلب من السائق الآن تصوير إثبات التسليم.") : Alert.alert("الرمز غير مكتمل", "أدخل أربعة أرقام.")} /><View style={styles.proofNotice}><Text style={styles.proofNoticeIcon}>▧</Text><View style={styles.flex}><Text style={styles.proofNoticeTitle}>صورة إثبات التسليم</Text><Text style={styles.proofNoticeCopy}>ستظهر هنا فور رفعها من السائق.</Text></View></View></View></View>;

  return <ScrollView contentContainerStyle={styles.scroll}><View style={styles.hero}><View><Text style={styles.eyebrow}>جربوع في حماة</Text><Text style={styles.heroTitle}>أهلاً، رامي</Text><Text style={styles.copy}>توصيل قريب وواضح وبالليرة السورية الجديدة.</Text></View><Mark /></View><HamaMap compact /><View style={styles.space}><Heading eyebrow="الخدمة متاحة" title="إلى أين نوصلك اليوم؟" /><Action title="إنشاء طلب توصيل" onPress={() => setPage("order")} /><View style={styles.note}><Text style={styles.noteIcon}>↗</Text><View style={styles.flex}><Text style={styles.noteTitle}>العناوين ضمن حماة فقط</Text><Text style={styles.noteCopy}>نقبل العناوين المحلية الموثقة للحفاظ على دقة التوصيل.</Text></View></View><Heading eyebrow="آخر الطلبات" title="لا توجد طلبات نشطة" aside="عرض السجل" /><View style={styles.empty}><Text style={styles.emptyText}>ستظهر حالة طلبك وتفاصيل السائق هنا فور التأكيد.</Text></View></View></ScrollView>;
}

function StopButtons({ current, setCurrent, choices }: { current: string; setCurrent: (value: string) => void; choices: readonly string[] }) {
  return <View style={styles.stops}>{choices.map((stop) => <Pressable key={stop} onPress={() => setCurrent(stop)} style={[styles.stop, current === stop && styles.stopSelected]}><Text style={[styles.stopText, current === stop && styles.stopTextSelected]}>{stop.replace("، حماة", "")}</Text></Pressable>)}</View>;
}

function Driver() {
  const [page, setPage] = useState<DriverPage>("home");
  const [personal, setPersonal] = useState<string | null>(null);
  const [identity, setIdentity] = useState<string | null>(null);
  const [proof, setProof] = useState<string | null>(null);
  const [code, setCode] = useState("");
  const [otp, setOtp] = useState("");
  const camera = async (which: "personal" | "identity" | "proof") => { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) return Alert.alert("إذن الكاميرا مطلوب", "يلزم الإذن لالتقاط الصور المطلوبة."); const result = await ImagePicker.launchCameraAsync({ allowsEditing: true, aspect: [4, 3], quality: 0.7 }); if (result.canceled) return; const uri = result.assets[0].uri; if (which === "personal") setPersonal(uri); if (which === "identity") setIdentity(uri); if (which === "proof") setProof(uri); };

  if (page === "verify") return <ScrollView contentContainerStyle={styles.scroll}><Top title="تفعيل السائق" back={() => setPage("home")} /><View style={styles.space}><Tag>خطوة أمان مطلوبة</Tag><Heading title="وثّق ملفك قبل القيادة" /><Text style={styles.copyRight}>تُراجع الصور من الإدارة، ولا يراها أي سائق آخر أو عميل.</Text><Upload title="صورة شخصية" detail={personal ? "تم الالتقاط" : "التقط صورة واضحة للوجه"} uri={personal} onPress={() => camera("personal")} /><Upload title="صورة الهوية" detail={identity ? "تم الالتقاط" : "تُخزّن في مساحة خاصة"} uri={identity} onPress={() => camera("identity")} /><Text style={styles.label}>كود التفعيل من الإدارة</Text><TextInput style={styles.input} value={code} onChangeText={setCode} placeholder="أدخل الكود" placeholderTextColor="#AAA" keyboardType="number-pad" textAlign="center" /><Action title="تأكيد التفعيل" onPress={() => !personal || !identity || code.length < 4 ? Alert.alert("بانتظار التفعيل", "ارفع الوثيقتين ثم أدخل كود التفعيل من الإدارة.") : (setPage("home"), Alert.alert("تم التفعيل", "أصبحت جاهزاً لرؤية الطلبات القريبة."))} /></View></ScrollView>;

  if (page === "drive") return <View style={styles.drive}><View style={styles.split}><Tag status>رحلة نشطة</Tag><Text style={styles.driveNumber}>#J-2048</Text></View><View><Text style={styles.driveLabel}>الشارع التالي</Text><Text style={styles.street}>شارع النواعير</Text><Text style={styles.distance}>١٫٣</Text><Text style={styles.distanceLabel}>كم متبقية</Text><View style={styles.progress}><View style={styles.progressFill} /></View><Text style={styles.driveHint}>المصدر: ساحة العاصي · العميل: رامي م.</Text></View><View style={styles.driveBottom}><View style={styles.utilityRow}><Pressable onPress={() => Alert.alert("اتصال", "سيُفتح اتصال العميل عند ربط أرقام الخدمة.")} style={styles.utility}><Text style={styles.utilityText}>اتصال</Text></Pressable><Pressable onPress={() => Alert.alert("دردشة", "ستظهر محادثة الطلب النصية هنا.")} style={styles.utility}><Text style={styles.utilityText}>دردشة</Text></Pressable></View><Action title="تم التوصيل" kind="dark" onPress={() => setPage("deliver")} /></View></View>;

  if (page === "deliver") return <ScrollView contentContainerStyle={styles.scroll}><Top title="إتمام التسليم" back={() => setPage("drive")} /><View style={styles.space}><DeliveryStep number="١" title="تحقق من رمز العميل" detail="لا تلتقط الصورة قبل مطابقة الرمز." /><TextInput style={styles.input} value={otp} onChangeText={setOtp} maxLength={4} keyboardType="number-pad" placeholder="رمز من ٤ أرقام" placeholderTextColor="#AAA" textAlign="center" /><DeliveryStep number="٢" title="صورة عند الباب" detail="تُرسل للعميل كإثبات التسليم فقط." /><Pressable onPress={() => camera("proof")} style={styles.cameraBox}>{proof ? <Image source={{ uri: proof }} style={styles.photo} contentFit="cover" /> : <><Text style={styles.cameraIcon}>◉</Text><Text style={styles.cameraText}>التقط صورة إثبات التسليم</Text></>}</Pressable><Action title="تأكيد التسليم ورفع الصورة" onPress={() => otp.length !== 4 || !proof ? Alert.alert("ينقصك إجراء", "تحقق من الرمز والتقط صورة الإثبات.") : (setPage("home"), Alert.alert("تم التسليم", "أُضيف الطلب إلى ورديتك اليوم."))} /></View></ScrollView>;

  return <ScrollView contentContainerStyle={styles.scroll}><View style={styles.driverHero}><View><Text style={styles.driverEyebrow}>وضع السائق</Text><Text style={styles.driverHeroTitle}>جاهز للانطلاق؟</Text><Text style={styles.driverHeroCopy}>طلبات واضحة وأزرار كبيرة أثناء القيادة.</Text></View><Tag status>متصل</Tag></View><View style={styles.space}><View style={styles.setup}><View style={styles.flex}><Text style={styles.setupTitle}>ملف التفعيل</Text><Text style={styles.setupCopy}>ارفع الوثائق ثم أدخل كود الإدارة.</Text></View><Action title="الوثائق" kind="outline" onPress={() => setPage("verify")} /></View><Heading eyebrow="طلبات قريبة" title="طلب واحد متاح" /><View style={styles.orderCard}><View style={styles.split}><Tag>٢٫١ كم</Tag><Text style={styles.orderPrice}>{formatSyp(12000)}</Text></View><Text style={styles.orderRoute}>ساحة العاصي ← باب البلد</Text><Text style={styles.copyRight}>٤٫٢ كم · نقدي · استلام الآن</Text><Action title="قبول الطلب وبدء الرحلة" onPress={() => setPage("drive")} /></View><View style={styles.shift}><Text style={styles.shiftTitle}>وردية اليوم</Text><Text style={styles.shiftValue}>{formatSyp(0)}</Text><Text style={styles.setupCopy}>تظهر التسوية عند إغلاق الوردية من الإدارة.</Text></View></View></ScrollView>;
}

function Upload({ title, detail, uri, onPress }: { title: string; detail: string; uri: string | null; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.upload}>{uri ? <Image source={{ uri }} style={styles.uploadPhoto} contentFit="cover" /> : <View style={styles.uploadPlaceholder}><Text style={styles.uploadSymbol}>＋</Text></View>}<View style={styles.flex}><Text style={styles.uploadTitle}>{title}</Text><Text style={styles.uploadDetail}>{detail}</Text></View></Pressable>; }
function DeliveryStep({ number, title, detail }: { number: string; title: string; detail: string }) { return <View style={styles.deliveryStep}><Text style={styles.stepNumber}>{number}</Text><View><Text style={styles.stepTitle}>{title}</Text><Text style={styles.stepDetail}>{detail}</Text></View></View>; }

function Admin() {
  const [approved, setApproved] = useState(false); const [closed, setClosed] = useState(false); const [downloaded, setDownloaded] = useState(false);
  return <ScrollView contentContainerStyle={styles.scroll}><View style={styles.adminHero}><View><Text style={styles.eyebrow}>لوحة الإدارة</Text><Text style={styles.adminTitle}>صباح الخير، مدير جربوع</Text><Text style={styles.copy}>مراقبة التشغيل والتسويات من مكان واحد.</Text></View><Mark /></View><View style={styles.metrics}><Metric value="١٨" label="طلباً اليوم" /><Metric value="٤" label="سائقون نشطون" /><Metric value={formatSyp(198000)} label="إيراد اليوم" /></View><View style={styles.space}><Heading eyebrow="المتابعة المباشرة" title="الخريطة الحية" aside="٤ سائقين" /><HamaMap compact driver /><Heading eyebrow="تحتاج قراراً" title="طلبات تحقق السائقين" /><View style={styles.task}><View style={styles.taskAvatar}><Text style={styles.taskAvatarText}>م</Text></View><View style={styles.flex}><Text style={styles.taskTitle}>محمد خ.</Text><Text style={styles.taskCopy}>{approved ? "تمت الموافقة · كود التفعيل جاهز" : "رفع صورة شخصية وهوية الآن"}</Text></View>{approved ? <Tag status>موافق</Tag> : <Pressable onPress={() => { setApproved(true); Alert.alert("تمت الموافقة", "تم إنشاء كود تفعيل للسائق في حسابه."); }} style={styles.smallAction}><Text style={styles.smallActionText}>موافقة</Text></Pressable>}</View><Heading eyebrow="التسوية اليومية" title="وردية سليم ع." /><View style={styles.settle}><View><Text style={styles.settleLabel}>إجمالي المستحقات</Text><Text style={styles.settleValue}>{formatSyp(76000)}</Text><Text style={styles.settleDetail}>{closed ? "أغلقت · شام كاش" : "نقدي · ٦ طلبات مكتملة"}</Text></View>{closed ? <Tag status>مغلقة</Tag> : <Pressable onPress={() => { setClosed(true); Alert.alert("أغلقت الوردية", "سُجّل الاستلام عبر شام كاش."); }} style={styles.closeButton}><Text style={styles.closeText}>إغلاق الوردية</Text></Pressable>}</View><Heading eyebrow="أرشفة شهرية" title="تقرير تموز ٢٠٢٦" /><View style={styles.report}><View style={styles.pdf}><Text style={styles.pdfText}>PDF</Text></View><View style={styles.flex}><Text style={styles.reportTitle}>{downloaded ? "تم تأكيد التنزيل" : "جاهز للتنزيل"}</Text><Text style={styles.reportCopy}>{downloaded ? "الحذف المؤجل لن يبدأ إلا بعد هذا التأكيد المسجّل." : "٢٨٤ طلباً · ١٧ ملغى · تفصيل الورديات"}</Text></View>{downloaded ? <Tag status>مؤكد</Tag> : <Pressable onPress={() => { setDownloaded(true); Alert.alert("تم تأكيد التنزيل", "ستقرأ المهمة الشهرية هذا التأكيد قبل حذف بيانات الشهر."); }} style={styles.smallAction}><Text style={styles.smallActionText}>تنزيل</Text></Pressable>}</View></View></ScrollView>;
}

function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Top({ title, back }: { title: string; back: () => void }) { return <View style={styles.top}><Pressable onPress={back} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.topTitle}>{title}</Text><View style={styles.backBlank} /></View>; }

export function Jarbou3App() { const [role, setRole] = useState<Role>("customer"); return <View style={styles.root}><RoleSwitch role={role} onSelect={setRole} />{role === "customer" ? <Customer /> : role === "driver" ? <Driver /> : <Admin />}</View>; }

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#F5F5F5" }, scroll: { paddingBottom: 30 }, fill: { flex: 1 }, flex: { flex: 1 }, pressed: { opacity: 0.78, transform: [{ scale: 0.986 }] }, space: { paddingHorizontal: 16, paddingTop: 16, gap: 14 }, roleSwitch: { flexDirection: "row-reverse", gap: 4, marginHorizontal: 16, marginTop: 8, marginBottom: 8, backgroundColor: "#E4E4E4", padding: 4, borderRadius: 14 }, role: { flex: 1, paddingVertical: 9, borderRadius: 10, alignItems: "center" }, roleSelected: { backgroundColor: "#FFF" }, roleText: { color: "#747474", fontSize: 13, fontWeight: "800" }, roleTextSelected: { color: dark },
  action: { minHeight: 53, borderRadius: 16, backgroundColor: gray, justifyContent: "center", alignItems: "center", paddingHorizontal: 14 }, actionDark: { backgroundColor: "#FFF" }, actionOutline: { backgroundColor: "transparent", borderWidth: 1, borderColor: "#C9C9C9" }, actionText: { color: "#FFF", fontSize: 14, fontWeight: "900", textAlign: "center" }, actionOutlineText: { color: gray }, tag: { backgroundColor: "#E9E9E9", paddingHorizontal: 9, paddingVertical: 5, borderRadius: 99, alignSelf: "flex-start" }, tagStatus: { backgroundColor: "#DDF2E9" }, tagText: { color: "#555", fontSize: 10, fontWeight: "900" }, tagStatusText: { color: "#276149" },
  mark: { width: 56, height: 56, borderRadius: 18, overflow: "hidden", backgroundColor: "#FFF" }, markSmall: { width: 34, height: 34, borderRadius: 11 }, markImage: { width: "100%", height: "100%" }, hero: { marginHorizontal: 16, padding: 19, borderRadius: 24, backgroundColor: "#FFF", flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, heroTitle: { color: dark, fontSize: 24, fontWeight: "900", textAlign: "right" }, eyebrow: { color: "#747474", fontSize: 11, fontWeight: "900", textAlign: "right", marginBottom: 4 }, copy: { color: "#737373", textAlign: "right", fontSize: 12, lineHeight: 19, marginTop: 4 }, copyRight: { color: "#737373", textAlign: "right", fontSize: 12, lineHeight: 19 },
  map: { height: 220, borderRadius: 23, overflow: "hidden", backgroundColor: "#D6D8D3", marginHorizontal: 16, marginTop: 16, position: "relative" }, mapCompact: { height: 188 }, nativeMap: { flex: 1 }, mapRoad: { position: "absolute", height: 4, left: -30, right: -30, backgroundColor: "#FFF", opacity: 0.75 }, mapName: { position: "absolute", top: 18, left: 20, color: "#747474", fontSize: 18, fontWeight: "900" }, dot: { position: "absolute", width: 12, height: 12, borderRadius: 8, borderWidth: 2, borderColor: "#FFF", backgroundColor: "#888" }, dotTarget: { width: 20, height: 20, borderRadius: 10, right: "12%", top: "20%", backgroundColor: "#2F7A62" }, mapDriver: { position: "absolute", top: "37%", left: "54%", borderWidth: 3, borderColor: "#FFF", borderRadius: 14 }, mapBadge: { position: "absolute", bottom: 11, right: 11, backgroundColor: "#FFFFFFE8", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10 }, mapBadgeText: { color: gray, fontSize: 11, fontWeight: "900" },
  headingRow: { flexDirection: "row-reverse", alignItems: "flex-end", justifyContent: "space-between" }, heading: { color: dark, fontSize: 19, fontWeight: "900", textAlign: "right" }, aside: { color: "#737373", fontSize: 11, fontWeight: "800" }, note: { backgroundColor: "#E7E7E7", borderRadius: 18, padding: 14, flexDirection: "row-reverse", gap: 10, alignItems: "center" }, noteIcon: { color: "#FFF", backgroundColor: gray, width: 35, height: 35, borderRadius: 11, overflow: "hidden", textAlign: "center", textAlignVertical: "center", fontSize: 19, fontWeight: "900" }, noteTitle: { color: dark, fontSize: 13, fontWeight: "900", textAlign: "right" }, noteCopy: { color: "#737373", fontSize: 11, lineHeight: 17, textAlign: "right", marginTop: 2 }, empty: { backgroundColor: "#FFF", borderRadius: 18, borderColor: "#D8D8D8", borderWidth: 1, borderStyle: "dashed", padding: 16 }, emptyText: { color: "#737373", fontSize: 12, textAlign: "right" },
  top: { height: 60, paddingHorizontal: 16, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, back: { width: 38, height: 38, borderRadius: 14, backgroundColor: "#FFF", alignItems: "center", justifyContent: "center" }, backText: { color: dark, fontSize: 30, marginTop: -6 }, backBlank: { width: 38 }, topTitle: { color: dark, fontSize: 17, fontWeight: "900" }, card: { backgroundColor: "#FFF", margin: 16, padding: 17, borderRadius: 23, gap: 11 }, label: { color: gray, fontSize: 12, fontWeight: "900", textAlign: "right", marginTop: 3 }, stops: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7 }, stop: { borderWidth: 1, borderColor: "#D8D8D8", borderRadius: 12, paddingHorizontal: 10, paddingVertical: 8 }, stopSelected: { borderColor: gray, backgroundColor: gray }, stopText: { color: "#717171", fontSize: 11, fontWeight: "800" }, stopTextSelected: { color: "#FFF" }, quote: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", backgroundColor: "#F0F0F0", borderRadius: 16, padding: 13 }, quoteLabel: { color: "#747474", fontSize: 10, fontWeight: "800", textAlign: "right" }, quoteValue: { color: dark, fontSize: 17, fontWeight: "900", marginTop: 3, textAlign: "right" }, quoteValueSmall: { color: gray, fontSize: 12, fontWeight: "800", marginTop: 3, textAlign: "right" }, quoteLine: { width: 1, height: 35, backgroundColor: "#D3D3D3" }, paymentRow: { flexDirection: "row-reverse", gap: 9 }, payment: { flex: 1, minHeight: 54, justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: "#D8D8D8", borderRadius: 15 }, paymentSelected: { borderWidth: 2, borderColor: gray, backgroundColor: "#F1F1F1" }, paymentText: { color: gray, fontSize: 12, fontWeight: "900" },
  trackSheet: { flex: 1, padding: 19, paddingTop: 12, backgroundColor: "#FFF", marginTop: -18, borderTopLeftRadius: 26, borderTopRightRadius: 26, gap: 12 }, handle: { width: 40, height: 4, borderRadius: 2, backgroundColor: "#D8D8D8", alignSelf: "center" }, split: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, muted: { color: "#737373", fontSize: 11, fontWeight: "700" }, trackTitle: { color: dark, fontSize: 22, fontWeight: "900", textAlign: "right" }, driverBox: { backgroundColor: "#F2F2F2", borderRadius: 18, padding: 12, flexDirection: "row-reverse", gap: 10, alignItems: "center" }, avatar: { width: 40, height: 40, borderRadius: 13, backgroundColor: gray, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFF", fontSize: 17, fontWeight: "900" }, driverName: { color: dark, fontSize: 13, fontWeight: "900", textAlign: "right" }, mutedRight: { color: "#737373", fontSize: 10, marginTop: 3, textAlign: "right" }, minor: { backgroundColor: "#FFF", borderRadius: 11, paddingHorizontal: 10, paddingVertical: 8 }, minorText: { color: gray, fontSize: 11, fontWeight: "900" }, timeline: { gap: 7, paddingRight: 6 }, done: { color: "#2F7A62", textAlign: "right", fontSize: 12, fontWeight: "800" }, live: { color: dark, textAlign: "right", fontSize: 12, fontWeight: "900" }, future: { color: "#AAA", textAlign: "right", fontSize: 12, fontWeight: "800" },
  centered: { padding: 28, alignItems: "center", gap: 15 }, otpBadge: { width: 100, height: 100, borderRadius: 50, backgroundColor: "#E9E9E9", borderColor: "#FFF", borderWidth: 8, alignItems: "center", justifyContent: "center" }, otpBadgeText: { color: gray, fontSize: 18, fontWeight: "900" }, centerTitle: { color: dark, fontSize: 22, fontWeight: "900", textAlign: "center" }, centerCopy: { color: "#737373", fontSize: 12, lineHeight: 19, textAlign: "center" }, otp: { width: "100%", backgroundColor: "#FFF", borderWidth: 1, borderColor: "#D8D8D8", borderRadius: 17, padding: 15, fontSize: 22, letterSpacing: 8, color: dark, fontWeight: "900" }, proofNotice: { width: "100%", backgroundColor: "#FFF", borderRadius: 17, padding: 13, flexDirection: "row-reverse", alignItems: "center", gap: 11 }, proofNoticeIcon: { color: "#A6A6A6", fontSize: 28 }, proofNoticeTitle: { color: gray, fontSize: 12, fontWeight: "900", textAlign: "right" }, proofNoticeCopy: { color: "#737373", fontSize: 10, textAlign: "right", marginTop: 3 },
  driverHero: { backgroundColor: "#242424", marginHorizontal: 16, padding: 19, borderRadius: 23, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, driverEyebrow: { color: "#B5B5B5", fontSize: 11, fontWeight: "900", textAlign: "right", marginBottom: 4 }, driverHeroTitle: { color: "#FFF", fontSize: 22, fontWeight: "900", textAlign: "right" }, driverHeroCopy: { color: "#CECECE", fontSize: 11, lineHeight: 18, textAlign: "right", marginTop: 4 }, setup: { backgroundColor: "#FFF", borderRadius: 18, padding: 13, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, setupTitle: { color: dark, fontSize: 13, fontWeight: "900", textAlign: "right" }, setupCopy: { color: "#737373", fontSize: 10, marginTop: 3, textAlign: "right" }, orderCard: { backgroundColor: "#FFF", borderRadius: 21, padding: 17, gap: 10 }, orderPrice: { color: dark, fontSize: 17, fontWeight: "900" }, orderRoute: { color: dark, fontSize: 16, fontWeight: "900", textAlign: "right" }, shift: { backgroundColor: "#E5E5E5", borderRadius: 18, padding: 15 }, shiftTitle: { color: gray, fontSize: 12, fontWeight: "900", textAlign: "right" }, shiftValue: { color: dark, fontSize: 22, fontWeight: "900", textAlign: "right", marginTop: 4 }, upload: { minHeight: 83, backgroundColor: "#FFF", borderRadius: 18, padding: 12, flexDirection: "row-reverse", alignItems: "center", gap: 11 }, uploadPhoto: { width: 57, height: 57, borderRadius: 13 }, uploadPlaceholder: { width: 57, height: 57, borderRadius: 13, backgroundColor: "#EFEFEF", alignItems: "center", justifyContent: "center" }, uploadSymbol: { color: "#777", fontSize: 29 }, uploadTitle: { color: dark, fontSize: 13, fontWeight: "900", textAlign: "right" }, uploadDetail: { color: "#737373", fontSize: 10, textAlign: "right", marginTop: 4 }, input: { minHeight: 52, borderRadius: 16, backgroundColor: "#FFF", borderColor: "#D8D8D8", borderWidth: 1, color: dark, fontWeight: "900", fontSize: 16, paddingHorizontal: 13 },
  drive: { flex: 1, backgroundColor: "#171717", padding: 22, justifyContent: "space-between" }, driveNumber: { color: "#A8A8A8", fontSize: 11, fontWeight: "800" }, driveLabel: { color: "#ABABAB", fontSize: 14, textAlign: "right", fontWeight: "800", marginTop: 30 }, street: { color: "#FFF", fontSize: 34, fontWeight: "900", textAlign: "right", marginTop: 3 }, distance: { color: "#FFF", fontSize: 78, lineHeight: 86, fontWeight: "900", textAlign: "center", marginTop: 24 }, distanceLabel: { color: "#C6C6C6", fontSize: 14, textAlign: "center", fontWeight: "800" }, progress: { height: 11, backgroundColor: "#444", borderRadius: 6, overflow: "hidden", marginTop: 24 }, progressFill: { width: "68%", height: "100%", borderRadius: 6, backgroundColor: "#E5E5E5" }, driveHint: { color: "#C6C6C6", fontSize: 12, textAlign: "center", marginTop: 17 }, driveBottom: { gap: 13 }, utilityRow: { flexDirection: "row-reverse", gap: 10 }, utility: { flex: 1, height: 55, borderRadius: 17, borderWidth: 1, borderColor: "#5B5B5B", justifyContent: "center", alignItems: "center" }, utilityText: { color: "#FFF", fontSize: 15, fontWeight: "900" },
  deliveryStep: { flexDirection: "row-reverse", alignItems: "center", gap: 11 }, stepNumber: { width: 33, height: 33, borderRadius: 17, backgroundColor: gray, color: "#FFF", fontWeight: "900", textAlign: "center", textAlignVertical: "center" }, stepTitle: { color: dark, fontSize: 14, fontWeight: "900", textAlign: "right" }, stepDetail: { color: "#737373", fontSize: 10, marginTop: 3, textAlign: "right" }, cameraBox: { height: 174, backgroundColor: "#FFF", borderColor: "#C8C8C8", borderWidth: 1.5, borderStyle: "dashed", borderRadius: 21, overflow: "hidden", justifyContent: "center", alignItems: "center", gap: 6 }, cameraIcon: { fontSize: 34, color: "#777" }, cameraText: { color: gray, fontSize: 12, fontWeight: "900" }, photo: { width: "100%", height: "100%" },
  adminHero: { marginHorizontal: 16, backgroundColor: "#FFF", padding: 18, borderRadius: 23, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, adminTitle: { color: dark, fontSize: 19, fontWeight: "900", textAlign: "right" }, metrics: { margin: 16, marginBottom: 0, flexDirection: "row-reverse", gap: 7 }, metric: { flex: 1, backgroundColor: "#E8E8E8", borderRadius: 15, paddingVertical: 12, paddingHorizontal: 6, alignItems: "center" }, metricValue: { color: dark, fontSize: 16, fontWeight: "900", textAlign: "center" }, metricLabel: { color: "#737373", fontSize: 9, fontWeight: "800", marginTop: 4, textAlign: "center" }, task: { backgroundColor: "#FFF", borderRadius: 18, padding: 13, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, taskAvatar: { width: 39, height: 39, borderRadius: 13, backgroundColor: "#E3E3E3", alignItems: "center", justifyContent: "center" }, taskAvatarText: { color: gray, fontSize: 16, fontWeight: "900" }, taskTitle: { color: dark, fontSize: 13, fontWeight: "900", textAlign: "right" }, taskCopy: { color: "#737373", fontSize: 10, marginTop: 3, textAlign: "right" }, smallAction: { backgroundColor: gray, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10 }, smallActionText: { color: "#FFF", fontSize: 10, fontWeight: "900" }, settle: { backgroundColor: "#252525", borderRadius: 20, padding: 15, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between" }, settleLabel: { color: "#BEBEBE", fontSize: 10, fontWeight: "800", textAlign: "right" }, settleValue: { color: "#FFF", fontSize: 21, fontWeight: "900", textAlign: "right", marginTop: 3 }, settleDetail: { color: "#BEBEBE", fontSize: 10, textAlign: "right", marginTop: 3 }, closeButton: { borderWidth: 1, borderColor: "#747474", padding: 9, borderRadius: 11, maxWidth: 88 }, closeText: { color: "#FFF", fontSize: 10, fontWeight: "900", textAlign: "center" }, report: { backgroundColor: "#FFF", borderRadius: 18, padding: 13, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, pdf: { width: 45, height: 45, borderRadius: 14, backgroundColor: "#E9E9E9", alignItems: "center", justifyContent: "center" }, pdfText: { color: gray, fontSize: 10, fontWeight: "900" }, reportTitle: { color: dark, fontSize: 13, fontWeight: "900", textAlign: "right" }, reportCopy: { color: "#737373", fontSize: 10, lineHeight: 15, textAlign: "right", marginTop: 3 },
});
